#
# Zola-SSG Configuration
#

base_url = "/"
description = "Teaching Chickens how to Read"
title = "Readahead"

compile_sass = true
minify_html = true

[extra]
logo_title = "readahead"

[markdown]
highlight_code = true
